<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_Menu</name>
   <tag></tag>
   <elementGuidId>6de395c6-f574-4864-a056-819684b290ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
   </webElementProperties>
</WebElementEntity>
